# W02_0301

## Air Pollution Decision Tools– Introduction



Air pollution results from myriad sources and processes.
This information must be evaluated and integrated to inform decision makers as to the best approaches for addressing the problems presented by polluted air.
The information in the figure indicates that air pollution is not a single variable, linear relationship between sources and receptors.
Indeed, activities that one may assume would increase emissions, such as increased energy consumption and vehicle miles travelled, were accompanied by substantial decreases in the emissions of criteria air pollutants.

The relationships between risk from air pollutants and sources can only properly be explained systematically. That is, the harm that results from air pollution is a product of the life cycle of pollution.
Air pollution is an outcome of the steps that involve energy and various types of matter, both living and non-living.
The life cycle includes not only time in the air, but also time in the water, on the land, in the soil, and within organisms. 
The emission of an agent is only one part of the life cycle. Indeed, it is not even the beginning, since certain processes always precede the emission.

environmental and health policies are made from two broad perspectives: 
evidence-based risk assessments.
Precaution.
For evidence-based decisions, the onus is mainly placed on proving that a product or process causes harm, whereas in precaution-based decision making, the onus is placed on proving something is safe or will not cause harm.
The precaution usually includes an element of irreversibility, i.e. even a slight chance that an agent will cause irreversible harm would lead to a decision not to allow the agent, or at least only allow it at levels below which there is strong scientific information showing no harm.

Both evidence-based and precaution-based decisions require the analysis of substantial amounts of data.
Evidence-based risk assessments require information regarding both the hazard and the likelihood of exposure to that hazard. Thus, if this information is scarce or unreliable, the risk assessment is useless at best and dangerous at worst, since it either underestimates or overestimates the risk.
For problems that may affect large numbers of people, large geographic areas, and/or that are irreversible, precaution is in order.
This is the basis for factors of safety in engineering design and prudence. Therefore, precaution applies to global scale air pollution, such as the long-range transport of pollutants, acid rain, and climate change (Figure). 

One of the arguments for taking actions to address climate change is that climate change could be irreversible (given the long wait for sufficient evidence) and that under many predicted scenarios such change likely would lead to widespread and severe damage to public health and ecosystems.
The ecological effects include loss of diversity and productivity.
Some habitats are particularly vulnerable to irreversibility.
The understanding of the factors that lead to a risk is called risk analysis; whereas the reduction of this risk (e.g. by wearing helmet and staying on bike paths) is known as risk management.
Risk management, including the policies, laws, and other societal aspects of risk, is often differentiated from risk assessment, which comprises the scientific considerations of a risk.

Air pollution risk is increased in two very basic ways.
The mix of substances may become inherently more harmful; or the amount of exposure to harmful substances may increase. The former is an increase in the hazard and the latter is an increase in exposure.
Air pollution actions must be based on reliable risk analysis and assessment. 


## Air Pollution Decision Tools– Interpreting Data

Events can be characterized in a number of ways. Events may be discrete or continuous. Events can also be independent or dependent. 
Since air pollution usually involves numerous variables, joint probabilities are also calculated.
For n mutually exclusive events as possible outcomes from E that have probabilities equal to P{Ei}, the probability of these events in a trial equals the sum of the individual probabilities:

\(P(E_1 or E_2 \ldots,or E_k) = P(E_1)+P(E_2)+\cdots,+P(E_3)\)

Further this helps us to find the probabilities of events ei and gi for two independent sets of events, E and G, respectively:

\(P(e_i and g_i) = P(e_i)P(g_i)\)

---

For example, a company record book indicates that a waste site has 10 unlabelled buried chemical drums. However, the drums were originally colour coded according to the vapor pressures (P) of the contents:
five drums that contain a low vapor pressure (P0 = 10-6 kPa) substance (Plow), two drums that contain a medium vapor pressure (P0 = 10-4 kPa) substance (Pmed), and three drums that contain a very high vapor pressure (P0 = 10-1 kPa) substance (Pvh). 
To remove the Plow and Pmed drums before calling in special equip teams for the Plow drums that, if ruptured, would release the contents into the air more rapidly.
We can determine the probability of pulling up one of the drums that contains substances with a low or medium vapor pressure (i.e. Plow and Pmed). The two possible events (Plow drum or Pmed drum) then, are mutually exclusive and come from the same sample space


Thus we have a 70% probability of pulling up a drum with a low to moderate vapor pressure substance.

Following the above, A nearby waste site also has 10 unlabelled, buried drums, but with known chemical formulations: three drums that contain dichloromethane (CH2Cl2) and seven drums that contain trichloromethane (CHCl3).
If there is a possibility that the Pmed substance could be very dangerous in the presence of CHCl3, and the need for special measures to segregate the Pmed and CHCl3.
To know the probability of pulling up a Pmed drum from the first site and a CHCl3 drum from the second site. Since the two trials are independent, it can be calculated as 


Thus we have 6% probability of extracting a medium vapor pressure substance drum and a dichloromethane drum on our first excavation.
Thus, there will be a 6% probability of this scenario, unless other steps are taken (e.g. conducting removals on different days)


Another important concept for environmental data is that of conditional probability.
If we have two dependent sets of events, E and G, the probability that event ek will occur if the dependent event g has previously occurred is shown as p{ek | g}, which is found using Baye’s theorem:


A review of this equation shows that conditional probabilities are affected by a cascade of previous events.
Thus, the probability of what happens next can be highly dependent upon what has previously occurred. For example, the cumulative risk of cancer depends on the serial (dependent) outcomes.
Similarly, reliability can also be affected by dependencies and prior events. Thus, characterizing any risk or determining the reliability of systems are expressions, at least in part, of probability.


Air pollution data can also be presented by a “probability density function” (PDF) for data. 
The PDF is created from a probability density; when the data are plotted in the form of a histogram, as the amount of data increases, the graph increases its smoothness, i.e. the data appear to be continuous.
The smooth curve can be expressed mathematically as a function, f(x), which is the PDF.
The probability distribution can take many shapes, so the f(x) for each distribution will differ accordingly.
For example, in environmental matters, distributions commonly seen are normal, log-normal, and Poisson.

The normal (Gaussian) distribution is symmetrical and is best known as the “bell curve”, given its shape (as right Figure).
The log-normal distribution is also symmetrical, but its x-axis is plotted as a logarithm of the values.
The Poisson distribution is a representation of events that happen with relative infrequency, but regularly.
The Poisson distribution function expresses the probability of observing various numbers of a particular event in a sample when the mean probability of that event in any one trial is very small.
So, the Poisson probability distribution characterizes discrete events that occur independently of one another during a specific period of time.
This is useful for risk assessments, since exposure-related measurements can be expressed as a rate of discrete events, i.e. the number of times an event happens during a defined time interval, such as the frequency (times per week) that a person drives a car. 

The Poisson distribution describes events that take place during a fixed period of time (i.e. a rate), so long as the individual events are independent of one another.


The Poisson equation needed to compute the probability of a specific number of counts being observed over a defined time interval is


where, λ - average or expected counts or events per unit time and n - number of encounters.
Thus, the Poisson distribution is useful in a risk assessment to estimate exposures.
It may be used to characterize the frequency with which a person (or animal or ecosystem) comes into contact with a substance.

## Expressions of Air Pollution Risk

Expressions of Air Pollution Risk
An event (e) is one of the possible outcomes of a trial (drawn from a population). Risk is a probability.
All probabilities, including risk, range from zero to unity, or are stated as a percentage, 0-100%. 
Risks in a population can be stated as the product of probability and an outcome. 
This can be stated as a frequency (F) at which the adverse outcome occurs: 

where, X = number of adverse events; N = number of individuals in the population.

For example, if 100 people contact a disease randomly distributed in a population of 100,000, frequency of the disease is 102/105 = 10-3, or one in a thousand. The F term is usually referred to as a probability (P). 
Air pollution studies often compare populations, e.g. workers exposed to a particular air pollutant compared to the general population.
This comparison is known as a relative risk (RR), which is calculated as


RR for air pollutants is often stated as a ratio, particularly as a standard mortality ratio or a standard morbidity ratio (both abbreviated to “SMR”):

where, D = number of deaths for standardized mortality rates or number of diseases for standardized morbidity rates.

For example, if 15 out of 10,000 workers who are exposed to air polluted with a metallic compound have died of a type of lung cancer that occurs at a rate of 15 per million, the SMR for this hypothetical cohort of exposed workers would be 15(104)-1 / 15 (106) -1 = 102.
This means that the worker’s RR is 100 times that of the general population of dying from this particular type of cancer.
The SMR is used as a specific measure of the strength of association between a population’s exposure to an air pollutant and deaths that may be attributed to that exposure.
The mortality rate in a community without a specific exposure or intervention is called the baseline rate, which represents the expected level of the mortality.
Note that the denominators in Eqs (4.7) and (4.8) include “unexposed” in their subscripts. Actually, these populations are seldom completely unexposed.


Workplaces may differ from the general environment not only in the concentrations of certain pollutants, but also in the ways people are exposed. 
For example, the toxic metal **cadmium (Cd)** is a pollutant released during the production of batteries (especially, nickel-cadmium [NiCd] types), paints, and coatings, as well as during metal work, e.g. welding, soldering, and plating.
Air concentrations of Cd in the workplace can be much higher than in the general environment.
In the United States, inhalation is the major route of workplace exposure to Cd. The Occupational Safety and Health Administration has set the permissible exposure limit (PEL) for Cd fumes or cadmium oxide (CdO) as 0.1 µg m-3 .

### Risk Factors and Confounders

Risk Factors and Confounders
Another way to think about Ens (4.7) and (4.8) is that they show the difference between what is being observed versus what is expected in terms of death and disease.
The denominator actually needs to be comparable from one study to the next, i.e. a “standard population” or “reference population”.
So, the SMR is employed to compare mortality or morbidity risks of a study population to that of a standard population. 
The standard population may or may not be an unexposed population. For most air pollutants, the standard population is indeed exposed, but usually are much lower levels than the study group.
However, the standard population may actually be more highly exposed to certain air pollutants, such as O3 indoor is usually much lower than that outdoor.



## Causal Links between Risk Factors and Adverse Outcomes

Air pollution decision making must infer causality.
Risk of an adverse outcome is increased when risk factors are increased in number and size.
Two essential attributes of a risk factor is its strength of association and its temporality.

### Strength of Association

How to associate a particular risk factor, especially an air pollutant, with an adverse outcome?
Strong associations provide more certain evidence of causality than is provided by weak associations.
Common epidemiological metrics used in association include risk ratio, odds ratio, and standardized mortality ratio.

### Consistency

Has [the association] been repeatedly observed by different persons, in different places, circumstances and times?
Outcomes from laboratory-based and/or field work studies are consistent?!
Consistency strengthens the link between exposure to an air pollutant and an adverse effect, e.g. lung cancer.
Consider an air pollutant that is positive for mutagenicity, is linked to cancer in mouse and Rhesus monkey experiments, and for which human epidemiological studies show increased cancer incidence

### Specificity

The specificity criterion holds that the cause should lead to only one disease and that the disease should result from only this single cause.
This is rarely the case in studying most chronic diseases, since a chemical can be associated with cancers in numerous organs, and the same chemical may elicit cancer, hormonal, immunological, and neural dysfunctions.
In addition, non-chemical stressors may elicit the same chronic effects as chemicals, such as psychological stress and genetic disorders. Thus, for air pollution studies, specificity is not to be expected for many diseases.

### Temporality

Timing of exposure is critical to causality.
For air pollutants, the exposure begins the disease progression process. If the disease occurs before the exposure, the pollutant cannot be considered a cause of the disease.

Although the temporality is required for causality, it does not assure causality. That is, if the exposure to the air pollutant occurred after the onset of the disease, that study cannot be used as evidence linking the air pollutant to the disease
However, if the exposure occurred prior to the disease, the study may be used, but only if other criteria support the causal link, since another agent or risk factor may be the actual cause of the disease (confounders).


## Biologic Gradient

Chemical hazard is usually determined from bioassays, animal studies, epidemiology, and models that generate a biological gradient, i.e. the higher the dose the greater the effect. 
This is known as the “dose-response” step in risk assessment.
Dose-response curves point to thresholds above which air pollutant exposures are expected to elicit effects (e.g. above a “no observable adverse effect level”). 
Air pollution is hazardous to both human health and ecosystems, so the biological response may manifest itself as diseases and death in human populations and as damage to habitats and organisms living in ecosystems

### Coherence

All available evidence concerning the natural history and biology of the disease should “stick together” (cohere) to form a cohesive whole.
For air pollution, temporal patterns of exposure and adverse effects must adhere to what is known about the associated biological effects. 
If animal data suggest that inhaling a substance leads to a respiratory effect, but human data do not, this is an example of lack of coherence. 
Lack of coherence may be the result of paucity of human data; Lack of coherence may also result from intraspecies differences for which human studies have not yet been properly designed; Lack of coherence, then, does not in itself eliminate a causal link.
Conversely, if all studies are coherent, it very strongly suggests a causal link.

### Experimentation

Experimental evidence in support of a causal hypothesis may come in the form of community and clinical trials, in vitro and in vivo laboratory experiments, animal models, and natural experiments.
The relationship between an air pollutant and an adverse outcome is usually multifaceted. Slight differences in chemistry, physical form, and biological makeup of the receptor organism cannot usually be duplicated with well-controlled experiments. Thus, the results are usually very specific to the independent and dependent variables in study and not easily extrapolated to actual, real-world situations.

## Life Cycle Assessment of Air Pollutants– Systems Context for Air Pollution

- Life cycle assessment (LCA) is one increasingly useful and reliable tool for air pollution decision making.
- Air pollution must be understood systematically and includes steps that involve energy and various types of matter, both living and nonliving. 
- The life cycle perspective avoids arbitrary divisions among air pollution, water pollution, land pollution, and the like.
- The fundamentals include a sound basis for designing and selecting the appropriate air pollution control equipment or understanding the chemical reactions that lead to the emission of air pollutants.
- **Energy production** is a major source of air pollution.
Energy concerns are at the forefront of political, policy, and scientific decisions.

## Life Cycle Assessment of Air Pollutants– Energy

- Modern life depends on energy in all of its forms, including mechanical, thermal, chemical, acoustic, and nuclear energy. 
- Most of the earth’s available energy comes from the sun.
- The fusion and fission of the sun emits large amounts of electromagnetic radiation, some of which finds its way to the earth (i.e., sunlight). 
- Plants use and store this energy by photosynthesis; Animals use the stored energy for respiration; The remains of these plants and animals are deposited, and under pressure and over vast periods of time, energy is captured in minerals, known as **fossil fuels**.

- The sun is also the source of many so-called alternative energy sources. Most obvious is solar energy.
- Wind is actually a type of solar energy, since the heating of the atmosphere leads to air movements. 
- **Bioenergy systems**, e.g. algae and wood, are also solar, given that they derive their energy from photosynthesis and respiration.
- The only “nonsolar” energy source on the earth is nuclear energy; Radioactive elements have unstable nuclei that emit radiation as they decay.
- Choosing the best energy source is complicated. The most contentious and important are the public health and environmental impacts of the various energy sources.

- An electric car may appear to be much cleaner than a gasoline-powered car, based solely on tailpipe emissions. The comparison becomes more complicated when the major source of electricity is coal that, when burned, emits large amounts of pollution from a stationary source, i.e. **the power plant**.
- The best way to consider the air pollution impacts of energy production, distribution, and transport is to employ a **life cycle assessment (LCA)**.
- In the electricity versus internal combustion example, the electric car system would emit large amounts of particulate matter (PM), sulfur dioxide (SO2), nitrogen dioxide (NO2), and heavy metals (including mercury [Hg]) from a central source.
- Conversely, each gasoline-powered car would emit much smaller amounts of PM; volatile organic compounds (VOCs), like benzene; and other pollutants, but the overall emissions from millions of small mobile sources (vehicles) is what is important.

## Life Cycle Assessment of Air Pollutants– Energy Life Cycles

- The environmental acceptability of any energy source must be evaluated systematically. This is demonstrated by the **LCA** (see Figure).
- Burning 100-L fuel A to manufacture 1000 kg of product Y releasing 100 kg of SO2 per year versus burning 150 L of fuel B to manufacture the same amount of product Z, but releasing 300 kg of SO2 per year.
- If this were the only criterion, fuel A would unquestionably be the best choice. It uses 50% less fuel (more energy efficient) and releases one-third of the pollutant. 
- However, looking further back into the life cycle in Figure 5.1, It is found that fuel A requires that 1 t of earth is removed to produce 100 L of fuel A, but fuel B requires no extraction (it is generated from recycled food oils, e.g. biodiesel).
- It would appear that, early in the life cycle, fuel A has a much higher environmental cost (damage) than does fuel B. It could be that the extraction process does not emit a large amount of air pollutants, although such processes usually do, often in the form of fugitive dust (PM). 
- **Extraction activities** almost always damage ecosystems, soil, and water systems. Furthermore, the two fuels will have different costs and benefits at the other levels.
- **Spatial harm** occurs when a contaminant is released into the environment and causes immediate harm within a defined distance of the release. 
- For example, an atmospheric plume may be transported to places where it causes additional harm. Within the plume, chemical transformation may occur by abiotic and biotic processes to form new compounds, which may be more or less reactive and toxic and which may build up in the environment after they are deposited from the atmosphere.
- **Temporal harm** can take the form of short-term impacts.时间性伤害
- A substance is released into the environment, rendering an immediate, acute impact. Such a response can range from the highly circumscribed with little impact (e.g. release of a highly reactive substance in sufficiently low quantities and distance between the release and the receptor, so that it breaks down long before causing any harm) to disastrous (an immediate release of sufficiently large quantities of a substance that reach the receptor and elicit effects to a large population of receptors). 
- The insult may be either isolated or episodic (e.g. one-time event like thermal inversion during a confluence of events, such as an explosion, where large amounts of contaminants are released and remain for a protracted time period),
- or it may be continuous, e.g. a water heater that releases carbon monoxide due to inadequate air-to-gas ratios, a leak from a propane tank valve into the atmosphere, or a slow release of gasoline (benzeneetolueneeethylbenzeneexylene) from an underground storage tank over decades into the groundwater and atmosphere.
- The top box in Figure 5.2 includes emissions from every step in the energy life cycle, from **extraction** (e.g. PM from mining and volatilization of compounds from crude oil and natural gas extraction) to releases of air pollutants from **refining and processing** to emissions from vehicles and other sources during combustion to releases from landfills, incinerators, recycling, and other end-of-life systems.
- Mass must be balanced.

### Upstream Impacts

- Every energy source has upstream impacts.
- **Coal and uranium** must be mined, crude oil and natural gas drilled, and trees harvested.
- This also extends to “non-emitting” sources. 
- Construction of materials extracted from the earth.
- After extraction, the manufacturing processes are also part of the upstream stage of the life cycle for all energy sources, i.e., decentralized system, wind turbines installed on buildings, as well as related facility.
- The **footprint** of these large systems can be substantial in terms of time, materials, and energy demands. 

## Life Cycle Assessment of Air Pollutants– Environmental Justice during Extraction

- A complete LCA consideration must include societal factors. A particularly illustrative example is justice.
- **“Environmental justice”** communities have two characteristics: 
    1. They have experienced historical (usually multigenerational) exposures to disproportionately high doses of potentially harmful substances (the environmental part). 
    2. They have certain specified **socioeconomic and demographic characteristics** 社会经济学和人口学特征, including a low SES; are racial and ethnic; and are historically a disadvantaged people.


## Life Cycle Assessment of Air Pollutants– Fuel Cycle Impacts

- Some fuels are usable directly as extracted, e.g. natural gas and coal, but often need to be changed physically to aid transport and combustion. 
- The natural gas may be compressed for ease in cross-oceanic transport. Coal will be crushed and even pulverized, depending on the combustion requirements.
- Processing uranium ore into usable fuel may require large amounts of energy, often from fossil fuels. Thus, even though the nuclear reactions themselves produce no greenhouse gases or other pollutants, the processing steps certainly will.

### Life Cycle Assessment of Air Pollutants– Operation Stage

- After extraction and fuel processing, each energy system is operated over its design life. During this life, fossil fuels are burned, nuclear reactions occur, and biota grow. 
  
**Combustion** 燃烧（分解

The largest human-induced source of many air pollutants is the combustion of fossil fuels to generate electricity.
The principal contributor to Hg, CO2, and SO2 emissions has been coal-fired power plants.

- The interactions of ions in precipitation (i.e. H+, SO4-2 , NO3- ) with organic and inorganic constituents of soil and water affect toxicity. Particularly important is the leaching of potentially toxic elements, especially aluminum, from rocks and soils by acidic precipitation.
- Complete or efficient combustion (thermal oxidation) converts hydrocarbons to carbon dioxide and water:

- Combustion is the combination of O2 in the presence of heat (as in burning fuel), producing CO2 and H2O during complete combustion of organic compounds, such as the combustion of octane:

- Complete combustion may also result in the production of molecular nitrogen (N2) when nitrogen-containing organics are burned, such as in the combustion of methylamine

- Incomplete combustion can produce a variety of compounds. Some are more toxic than the original compounds being oxidized, such as polycyclic aromatic hydrocarbons (PAHs), dioxins, furans, and CO.
- Incomplete combustion reactions are very important sources of air pollutants.

## 空氣污染氣象學

- 大氣對污染物的四種作用: 
  1. 輸送作用: **風速、風向**決定污染物輸送範圍及大小
  2. 擴散作用: 主要指**垂直**方向的擴散，與地表粗糙度、大氣穩定度及混合層高度有關。
  3. 轉化作用: 污染物質於大氣中因自身衰減或與其他污染物或受陽光照射之作用，發生化學變化。轉化成其他物質而造成二次污染，如**光化學反應**。
  4. 移除作用: 大氣中之污染物質因下列過程而從大氣中消失。
        1. 微粒物質因重力而沉降至地表
        2. 因降雨或降雪的洗除
        3. 被雪粒、水蒸氣包圍而成凝結核。
- 上述作用中，以輸送效應最大，而影響大氣輸送最主要的因子為盛行風(Praevailing Wind).


- 影響大氣中空氣污染物輸送與擴散之因子

1. 大氣穩定度: 風速、風向、溫度梯度 (Temperature gradient)、日照、雲量等。
2. 混合層高度: 定義為地面上受到亂流作用而使污染物得以擴散至混合的高度。
3. 局部環流: 熱島效應、海陸風、下沖作用

- 氣壓與污染物之擴散
低壓地區常伴隨多雲且不穩定的天氣，風速亦較大，有利於污染物之擴散，其伴隨之雨水亦可移除大氣中之污染物。
高壓地區通常是晴朗穩定的天氣，風速亦較小，若有滯留高壓或沉降逆溫層的存在，則污染物之擴散及輸送均極不易，因此高污染事件好發於冬季。


### 風速與風向
- 風速
目前以計算有效煙囪高度處之風速，最簡便而常用的方法為利用風速冪次律(Power Law)。

- 風向
風向之定義為風的來向，通常將風向分為16個方位，並將逐時的風速大小描繪在該方向而形成**風花圖(Wind Rose)**。線條長短為風速出現的百分比。


### 大氣垂直溫度結構與安定度

- 溫降傾率(Lapse Rate)
當少量空氣在大氣層中向上移動，會因壓力降低而膨脹並降低溫度，通常該膨脹相當快速，可假設該氣團與周圍大氣間並未發生熱量轉移(假設為絕熱狀態)。



對一空氣圓柱，厚度差異dz所產生之靜態平衡如下:
    
dP = - $\rho gdz$               
                     (2-2)
                            
### 大氣溫降傾率與大氣穩定性之關係
1. Weak Lapse Rate – Weakly stable
大氣之盛行溫降傾率小於乾絕熱溫降傾率
(1)當氣團從C上升至A，氣團溫度T1低於大氣環境溫度T2，故氣團將在下降(因溫度低，密度較大，下降)
(2)氣團由C下降至B，氣團溫度T4高於大氣環境溫度T3，故氣團將在上升(因溫度高，密度較小，上升)
(3)此狀態為一穩定狀態，限制了氣團垂直運動，妨礙上下混合作用。


2. Strong Lapse Rate – Unstable
 大氣之盛行溫降傾率大於乾絕熱溫降傾率。
(1)當氣團從C上升至A，氣團溫度T2高於大氣環境溫度T1，故氣團將繼續上升。
(2)氣團由C下降至B，氣團溫度T3低於大氣環境溫度T4，故氣團將繼續下降。
(3)此狀態大氣垂直對流旺盛，利於污染物之擴散，系統為不穩定。

3. Neutral Stable
大氣之盛行溫降傾率等於乾絕熱溫降傾率。
氣團受外力後才有升降動作，若外力消失，則此氣團安定於新的位置，稱為中性穩定或隨意穩定。

結論
溫降傾率與大氣穩定性的關係如右圖

### 溫層逆轉
當高度升高時，氣溫亦隨之上升，亦即溫暖空氣在冷空氣上面，為一種弱溫降傾率之極端現象，空氣污染物無法向上擴散。

1. 輻射性逆轉(Radiation Inversion)
在良好氣候下，因陽光照射使地面溫度較高，藉由對流作用，氣溫高之空氣向上升，形成遞減現象；但在夜間，地面之熱能向較冷的天空輻射，地表溫度急速冷卻而上層空氣未循比例冷卻，稱為輻射逆轉。因其高度約在200公尺以下，故又稱為接地逆轉，隨著早晨日照之開始，逆轉消失。

2. 沉降性逆轉(Subsidence Inversion)
在高氣壓圈內，由於反旋風空氣之沉降，圈內空氣向外側吹，上層空氣沉降遞補，因絕熱壓縮，故沉降之空氣溫度會上升，因而形成逆轉。

3. 地形性逆轉
在谷地中，由於冷空氣沿著地表流入谷底之結果，使得空氣約接近地面溫度越低，越往上則溫度越高。於夜間又與輻射逆轉結合在一起，使逆轉更加擴大。


### 大氣安定度與煙柱型態（氣象學的部分和空氣污染有關）

煙柱之擴散與大氣之溫降傾率有關，煙柱之形狀可作為判定大氣條件是否安定之依據



### 地形與地理位置對煙流型態之影響

1. 溫暖而乾燥之區域(易輻射)
上午易發生燻煙型 (Fumigation)
下午傍晚，地面逆轉層易於形成，由煙囪高度(hs)決定煙流型態
Hs >= 逆轉層高度 - 屋頂型(Lofting)
Hs <=逆轉層高度 – 扇形(Faning)或侷煙型(Trapping)

2. 多雲而潮濕區域
盛行溫降傾率通常為濕絕熱型態(Wet Adiabatic Rate)，屬於弱溫降傾率(Weak Lapse Rate)的圓錐形(Coning)較常見。
3. 多雲的情況下
地面之輻射逆轉層不易形成。

### 混合層高度

基於地表因受熱而在垂直方向產生強烈的混合，並將熱量傳輸給大氣，其伸展至某高度直到受到逆溫層所阻擋，此高度即為混合層高度。

在混合層內，污染物所能垂直混合的上限高度即為混合層高度，主要決定於亂流混合的強度(與風速、風向、地面粗糙度、太陽照射、及大氣垂直溫度結構有關)。
1. 混合層高度最大值一般發生在午後2-3點，為排放氣體最佳時機
2. 混合層高度最小值一般發生在清晨5-6點。


### 局部環流對污染物的影響

- **熱島效應 (Heat Island)**: 由於鄉村與都市溫度差引起之局部環流。
由於都市之輻射程度較鄉村劇烈，都市上空有上升氣流，利於污染物之擴散及稀釋。然而，在夜間至日出之間，由於穩定度增加，阻止環流產生，使污染物靜止懸浮於都市上空，日出後都市上空之污染物阻止輻射熱之吸收，鄉村之增溫率較大，形成由鄉村吹向都市之局部環流，而都市上空則有下降氣流，不利污染物擴散，故在都會區晨間運動應盡量在日出前。
- **海陸風 (Land-Sea Circulation)**: 發生在海陸交界，以24小時為週期之一種空氣局地環流，因陸地與海洋熱力性質差異所引起。
白天時，因陸地地面之比熱較海水小(陸地加熱和冷卻速率都比水快)，故陸地上之空氣上升而海面上的空氣下降，形成海風環流而將海面上的污染物吹向內陸，增加地面污染。反之夜間形成陸風循環，將都市內污染物吹向海上，減輕地面污染。


- **下沖作用 (Down Wash)**: 氣流遇障礙物而在其背風處造成氣流的下降。下沖作用有以下兩種:
  1. 氣流遇障礙物而在其背風處造成細流的下沖
  2. 空氣動力效應引起之下沖作用，即廢氣之排放速度小於煙囪口之盛行風速，煙流未即上升即迅速被往下帶。當廢氣排放速度與風速比值大於1.5時，即可避免。
- **山谷風(Mountain-Valley Wind)**
因地形造成的局部環流，除了海陸風以外，另一種為山谷風，也是由不同冷卻程度所產生。在夜間，山谷中高度較高的地方其溫度較低，故空氣在夜間將流下到谷底，谷底的氣團被其上方的暖空氣困住，直到次日中午，股中空氣才有足夠熱量使逆轉瓦解。

- 海陸風及山谷風在氣象學上對空氣污染相當重要，因大型火力發電廠通常設在海岸或大湖附近。此情況下，煙囪之排放物在白天將由海風帶向內陸上空。而山谷中之污染源，白天煙柱將沿山谷上升，而晚上風吹向谷底，使煙柱由回到谷底，污染物濃度可能會累積到危險的程度




做都市規劃之時，應該先瞭解氣象條件！

老師説不要退選啦XD




