# W10_0426



工程師，主要考慮管末控制技術

污染物之類型：

- 粒狀
- 氣狀 gaseous air pollutant 以氣體的方式存在
  - organic
    - 環保法有嚴格的定義
    - VOC (Volatile Organic Compounds 揮發性有機化合物)
    - pah（環狀的Polycyclic Aromatic Hydrocarbons多環芳香烴）
  - non-organic
    - CO2 SO2
    - NO/NO2/N2O
    - metals (Hg)
  
針對不同類型的污染物，其控制技術差異甚大

擬定、制定污染控制策略，要完整考慮：

- 種類
- 量
  - 氣體的量【體積：1000m3】
  - 污染物的量【濃度：10ppm/1000ppm】
- 質

之後還要考慮設置成本

## 控制策略

控制策略

- Catalytic oxidation
- Incineration 燃燒
- Condensation 冷凝
- Absorption 吸收
- Adsorption 吸附
- Biofiltration 生物過濾
- photocatalysis 光催化

## Incineration 燃燒、焚化（c.f.樂色焚化（固體廢棄物，都市樂色是有熱質的，輔以一定程度的輔助燃料））

去除效率的目標，一定大於95，要到99%  
一般是用來處理低濃度、高毒性的有機氣體

the process of burning something completely

目的是物質的最終氧化態，destruction

不一定要氧作爲助燃劑。

主要針對有機物

需要混合足夠均匀、足夠的溫度、足夠的停留時間...  
3 conditions (3Ts): time, temperature, turbulence  
燃燒的效果才會夠好


要有燃料，最好產生的熱是可以被回收的

要讓燃燒發生，需要污染物的濃度要：

- 達到下限值
- 低於上限值

燃燒時往往要添加助燃劑

原污染氣體空氣量不足時，要補入空氣

燃料，一定是容易取得，好操作的

- 天然氣
- 石油（柴油

足夠的停留時間，才能然污染物被完全地破壞  
爲了停留時間變長，燃燒器的長度要增加，體積要增大，更占地方，也需要更多燃料  
所以燃燒器的大小要適中，  
工程設計是考量各個面嚮，權重，權衡之後得到的結果。  
一般不會停留超過2秒，不然燃燒器要很大

### Ignition

5個重點：

### 燃燒器設計

case1:

半導體，溶劑：A5H3溶度極低但毒性極高。

case2:

減少氮氧化物的生成

### 專有名詞

$\require{mhchem}$
$\ce{1CH4 + 2O2=1 CO2 +2H2O}$

- fuel rich 富燃，燃燒的燃料超過能夠捕入的，> $\ce{2O2}$
- fuel lean 貧燃，< $\ce{2O2}$

### 燃燒塔

對於化工廠、石化廠，停機或程序出現異常時，要趕快把原物料都清空，打到燃燒塔，快點燃燒掉。現在燃燒塔已經被限制為僅僅緊急狀態才能啓用。會產生黑烟。



## Condensation(seperation process)

heat exchange process  
冷凝、凝結 phase change  
絕大多數用在VOCs
適用於沸點高者。



不是所有的氣狀都可以 destruction  
e.g. $\ce{Hg}$

有回收價值、滿足可以回收的條件（好分離）

tolune 甲苯

15000ppm 

市場價格 200USD/kg

當然可以回收再利用，instead of 破壞掉，為公司節省成本

### condensor (cooler) 冷凝

合理地下降溫度、上升壓力

通常是做溫度的限制，而非加壓，因爲加壓的技術難度較高（要滿足密閉性的要求  
選擇是有限制性的。

降低其氣體飽和濃度

用熱力學公式計算

溫度的下降一定都是階段性的，不可能在單一設備做超大幅度的降溫，在進入condensor
的前階段，先進行一部分降溫，真正進入condensor的降溫幅度不會很大（是很小的），但是能夠有效地降低其氣體飽和濃度。

熱交換非常重要，熱交換做的不好，就會非常耗能。

Condensation是作爲前期處理，通常不是污染控制的最後端。很難作爲最後的一關，當作守門員，那難度很高（溫度要降到很低很低）。 
去除效率的Range 50-95%

冷媒的選用，依據溫度的範圍  
e.g. brine solution鹵水（水+鹽）凝固點低  
CFCs(Chlorofluorocarbons)用來處理\(\ce{Hg}\)要達到-40°C

#### 冷媒直接接觸氣體

缺點：若冷媒與氣體混合，混合產物還需要再分離， 可能會再產生二次污染  
有點：熱交換效率遠遠高於接觸式冷凝塔

#### 接觸式冷凝塔 surface condensation system

有一個surface隔開氣體和冷媒。 
主要用在回收，而非污染控制

#### cox chart

氣壓-沸點

#### 混合氣體

case1:  
toluene benzene xylene  
mixing solution

沸點不同，做蒸餾，分開，純度變高

case2:  
toluene water

沸點不同，做蒸餾，分開，

toluene非水溶性，本就不溶於水、會分層，可以做簡單的分離。

case3:
Methyl Ethyl Ketone + water

丁酮和水是互溶的。  
79.64 °C
沸點接近，往往會共沸，要分離就很難。
這時，冷凝就不是很好的做法。
但是台灣還是有在做。

分離的成本高，而沒有價值，可能就進入燃燒器，燒掉就好。


#### 地下油槽泄露

目的是土壤及地下水整治，而不是回收
 
地下污染團  
air sparging and sve

要把地下（地下水以上）的油氣趕出來 

- 濃度高，成分純：Condensation
- 濃度低，成分不純：燒掉

濃度不高，想回收？活性炭吸附塔。（下禮拜講）

各種控制設備的排列組合運用！

各種工程操作都沒有絕對的優劣，沒有標準答案，要能夠變通，有彈性


# W11_0503

$\require{mhchem}$

- Absorbtion 吸收
  - gas->liquid
  - 要找到一個liquid
  - 在很高的溫度、在很快的氣體流速，讓濃度很低的污染物被吸收到液體
    - 需要足夠的接觸時間
  - 世界上最好的溶劑就是水，但是水是極性的溶劑，不適合用於非極性的物質
- Adsorption 吸附
  - gas->solid

## 吸收

同質互溶

判斷 污染物是否適合吸收法

- 溶劑：便宜大量方便取得：水
  - 可以改變PH值
- 溶質：一定要親水hydrophilic

溶於水的物質常常就是用吸收法。

- 燃煤之後的洗滌塔， 去除 $\ce{CO2}$
- 半導體厰，去除 $\ce{IPA}$->對吸收之後的液體，再用高效率的分餾塔，去做分離

用有機溶劑做吸收？很少的情況，除非回收價值很高。

但如果回收價值很高，往往就用【吸附】

### 吸收塔的設計種類

吸收塔

- 吸收污染物（氣體->液體
- 先去除粒狀物
- 設備一定會降溫
  - 也有可能專門用來做降溫


太多種類的吸收塔，每種都有不同的功效

目的都是讓氣體和液體做均匀有效的接觸【增加接觸面積、延長停留時間】

要考慮壓損、scour（積垢）

積垢

$\ce{Ca(OH)2 + S2O -> CaSO4}$（永久硬度）

污染防治設備：越便宜、越堅固耐用越好

- packed column 填充塔【最常見】
  - random packing
  - structured packing
    - 較難保養【更換清潔】
  - 填充料
    - 最常見：塑膠PE
    - 陶瓷【溫度太高、酸堿度太强時】，但重量高，容易碎
    - 金屬【溫度很高很高時】價格高、重量高
- plate column
  - 很少使用，去除效率不好，主要是用於工業應用的回收
  - 主要用在化工廠、石化廠【氣體污染物濃度特別高】，回收氣體污染物
- miscellaneous

在氣體進入吸收塔之前，務必先把其中的粒狀物都去除，否則很快就要維護清潔吸收塔了。

## 吸附

gas(adsorbate) -> solid

需要一個有效的吸附劑【adsorber】有孔的材料，具有高的吸附能量，活性炭、沸石

同質互吸

也可以吸附水中的污染物，adsorbate：水中的重金屬、VOCs


非極性的物質就要找非極性的吸附材（活性炭，黑色的）
活性炭可以用來去除臭味，VOCs往往都有臭異味。

活性炭，一般都是重複再利用的，

但是如果，活性炭吸收了有害物質，就變成危害性廢棄物，依法規掩埋


油槽，油揮發，因高壓而減壓，排出來的氣，先經過活性炭吸附，再regenerate變成氣體，再冷凝，回收

## 生物濾床biofiltration

把VOCs作爲碳源，提供微生物的生長，要控制溫度、適度

在台灣越來越少，實體應用有難處，因爲其控制不容易，生物有不同類型

環保法規嚴格，較難符合

## 重點

各類設備：

- Incineration 燃燒
- Condensation 冷凝
- Absorption 吸收
- Adsorption 吸附
- （Biofiltration 生物過濾）

各自的使用條件、限制爲何？

最佳處理的排列組合爲何？


e.g. 
期末考

化纖工廠 

氣體流速、溫度 500 m^3/h 75°C

物質濃度：

- 1500 ppm 甲苯（單價低）
- 200 ppm MEK 丁酮（單價高）
- 50 ppm $\ce{H2S}$（有害物質非死不可）（無法冷凝）

（基於上述的四個技術）詳述理由，安排最合理的程序，要盡量做去除、回收，

不考慮成本